/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicHeader: typeof import('./components/BasicHeader.vue')['default']
    CodeDetail: typeof import('./components/CodeDetail.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MdEditor: typeof import('./components/MdEditor.vue')['default']
    MdView: typeof import('./components/MdView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
